### PR TITLE
feat (deployment): [rgs] follow the region resource recommendations

### PR DESCRIPTION
**Pull request by ferantivero**
- modify resource group creation to make the location part of the resource group's name
- modify network and cluster biceps to convert the location param to a variable defaulting to the rg location
- modify steps to use new naming convention and remove location argument

image

### CODE REVIEW

**Review by johndowns — COMMENTED** [review]
I've proposed a few small edits.

Question: do you think it's necessary to include the region in the resource group names? I'm thinking it might simplify things if we omit it, because all of the resource groups are in one region anyway, and it would reduce the number of places to change if you want to deploy to a region other than Central US. Any thoughts?

**Comment by ferantivero** [comment]
> I've proposed a few small edits.
> 
> Question: do you think it's necessary to include the region in the resource group names? I'm thinking it might simplify things if we omit it, because all of the resource groups are in one region anyway, and it would reduce the number of places to change if you want to deploy to a region other than Central US. Any thoughts?

Open to remove the location from the rg name if requested. Thing is same task had been carried on in many other repos already and they are following this convention. 

While I would agree this simplify our docs deployment steps, most probably (and the recommendation) is to include this information as part of the naming.

Open to go either way.

**Comment by johndowns** [comment]
OK, fair enough - if we're doing it consistently elsewhere then I'm happy to go with the standard approach.

**Comment by johndowns** [comment]
@ferantivero Would you be able to please resolve the conflict and sign off again when you're happy?

**Comment by ferantivero** [comment]
> @ferantivero Would you be able to please resolve the conflict and sign off again when you're happy?

this is now resolved @johndowns

**Review by johndowns — APPROVED** [review]

**Pull request merged**
