### PR TITLE
Deleting AzureAppGatewayAnalytics

### PR DESCRIPTION
**Pull request by v-fearam**
AzureAppGatewayAnalytics is deprecated and it avoid sucess deployment

### CODE REVIEW

**Comment by ckittel** [comment]
I don't think we should remove it in the regulated environment without replacing it with the workbook, otherwise we are taking away a security lens without putting in a replacement.

**Comment by v-fearam** [comment]
The AzureAppGatewayAnalytics  deploy issue is not transient as far I tested in baseline and multicluster. 
I didn't execute here, but I'm quite sure is not working the deploy.
I will move this PR to draft, I will see when I have time to do the complete change.

**Comment by ckittel** [comment]
Oh, if it's not transient, then by all means, this is fine to prevent any issues short term.  I just thought you found out that it was.  My misunderstanding.

**Review by ckittel — APPROVED** [review]
🚀  -- let's just make sure there is an item in the backlog, S5 or S6 is fine, to move to the new traffic analytics workbook.  Thanks!

**Comment by v-fearam** [comment]
Added ADO #427693
when deploy:
```
{
            "type": "Microsoft.OperationsManagement/solutions",
            "apiVersion": "2015-11-01-preview",
            "name": "[concat('AzureAppGatewayAnalytics(', variables('logAnalyticsWorkspaceName'),')')]",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[resourceId('Microsoft.OperationalInsights/workspaces', variables('logAnalyticsWorkspaceName'))]"
            ],
            "properties": {
                "workspaceResourceId": "[resourceId('Microsoft.OperationalInsights/workspaces', variables('logAnalyticsWorkspaceName'))]"
            },
            "plan": {
                "name": "[concat('AzureAppGatewayAnalytics(', variables('logAnalyticsWorkspaceName'),')')]",
                "product": "OMSGallery/AzureAppGatewayAnalytics",
                "promotionCode": "",
                "publisher": "Microsoft"
            }
        }
```
the error:
```
{
    "status": "Failed",
    "error": {
        "code": "InvalidOperationArgument",
        "message": "Enabling solution of type AzureAppGatewayAnalytics is not allowed"
    }
}
```
https://azure.microsoft.com/en-us/updates/azure-application-gateway-analytics-will-be-retired-on-29-february-2024/
To continue monitoring your Application Gateway resources, transition to [Azure Monitor Network insights workbook ](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/azure-networking-analytics#migrating-from-azure-gateway-analytics-solution-to-azure-monitor-workbooks)

**Pull request merged**
